# Generated by Django 3.0 on 2019-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('brand', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
