# Generated by Django 3.0 on 2019-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frozen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='FrozenItems',
        ),
    ]
