# Generated by Django 3.0 on 2019-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frozen', '0003_auto_20191212_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
