# Generated by Django 3.0 on 2019-12-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frozen', '0004_frozenitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenitem',
            name='type',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
